"""Entry point invoked by GitHub Copilot's hooks for the Traccia integration.

Registered via the hook config generated by `traccia copilot install-hooks`,
which always calls this module with the event name as an explicit CLI
argument, e.g.:

    python -m traccia.integrations.github_copilot.hook preToolUse

(GitHub's hooks reference does not guarantee the event name is present in
Copilot's stdin payload itself -- see docs/github-copilot-integration.md
Section 2 -- so the generated hook config passes it explicitly instead of
relying on that.)

SAFETY: `preToolUse` is documented as fail-CLOSED on a non-zero exit (other
than a deliberate `permissionDecision: "deny"`) -- see
docs/github-copilot-integration.md Section 6. This script must never exit
non-zero and must do no network I/O on this path, or it risks blocking (or
denying) a legitimate Copilot tool call because of a Traccia bug or a slow
network. Every code path below is wrapped so that any failure still results
in exit(0) and an empty `{}` decision (no opinion -- never overrides
Copilot's own permission/behavior).
"""
from __future__ import annotations

import json
import sys
from typing import List, Optional


def _run(argv: List[str]) -> None:
    event_name = argv[1] if len(argv) > 1 else None
    if not event_name:
        return

    from traccia.integrations.github_copilot import mapping, state
    from traccia import config as sdk_config

    # Fresh process every invocation: nothing from a parent process's
    # traccia.init() call is visible here, so config is read directly.
    try:
        cfg = sdk_config.load_config()
        enabled = cfg.instrumentation.github_copilot
        capture_content = cfg.instrumentation.github_copilot_capture_content
    except Exception:
        enabled = True
        capture_content = False

    if not enabled:
        return

    raw = sys.stdin.read()
    if not raw:
        return
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return
    if not isinstance(payload, dict):
        return

    session_id = payload.get("sessionId")
    if not session_id:
        return  # nothing to correlate this event to

    if event_name not in mapping.ALL_KNOWN_EVENTS:
        return  # forward-compatible: silently ignore events this version doesn't map yet

    payload = mapping.strip_content_fields(event_name, payload, capture_content)
    state.append_event(session_id, event_name, payload)

    if event_name in mapping.SESSION_END_EVENTS:
        _spawn_flush(session_id)


def _spawn_flush(session_id: str) -> None:
    """Kick off export in a detached background process so the network call
    never blocks this hook (which Copilot is waiting on)."""
    import subprocess

    try:
        subprocess.Popen(
            [
                sys.executable,
                "-m",
                "traccia.integrations.github_copilot.flush",
                "--session",
                session_id,
            ],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except Exception:
        pass  # an orphaned session is still recoverable via `traccia copilot flush --all`


def main(argv: Optional[List[str]] = None) -> int:
    argv = list(argv) if argv is not None else list(sys.argv)
    try:
        _run(argv)
    except BaseException:
        # See module docstring: a Traccia bug must never affect Copilot's own
        # decision, so nothing here is allowed to propagate.
        pass
    try:
        # Empty JSON = no permission override, no content modification, for
        # every event type this hook is registered against.
        sys.stdout.write("{}")
    except Exception:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
